### ISSUE TITLE
Adding an edit option?

### ISSUE THREAD

**Issue by wimvelzeboer** [jdomenechb/rust-ddd-example#2]
Thanks a lot for this repo, it helps me a great deal to understand DDD in Rust.

Would you be able to add an edit option? Where it can take an Id and update its value?

**Comment by jdomenechb** [comment]
I recently wanted to do some changes to the repository in order to be more DDD-strict. I will take the chance to implement the edit too ☺️

**Comment by wimvelzeboer** [comment]
That sounds great! Looking forward to see your changes!
Thanks!
